version: '3.9'

services:
  weather_cache:
#    image: jamer007/canadian_weather_rest:latest
    image: weather_cache
    ports:
      - "3003:3003"


  redis:
#    image: jamer007/canadian_weather_rest:latest
    image: redis
    ports:
      - '6380:6379'
    volumes:
      - redis:/data
volumes:
  redis:
    driver: local